org: david2407
app: customersapi
service: customersapi
frameworkVersion: "3"

custom:
  customersTableName: "customers-${sls:stage}"
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CustomersTable, Arn]
  environment:
    CUSTOMERS_TABLE: ${self:custom.customersTableName}

functions:
  create:
    handler: handlers/create.create
    events:
      - http:
          path: handlers
          method: post
          cors: true

  getAllByCredits:
    handler: handlers/getAllByCredits.getAllByCredits
    events:
      - http:
          path: handlers 
          method: get
          cors: true

resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.customersTableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
