org: david2407
app: customersapi
service: customersapi
frameworkVersion: "3"

custom:
  customersTableName: "customers-${sls:stage}"

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CustomersTable, Arn]
  environment:
    CUSTOMERS_TABLE: ${self:custom.customersTableName}

functions:
  create:
    handler: handlers/create.create
    events:
      - http:
          path: customers
          method: post
          cors: true

  getById:
    handler: handlers/get.get
    events:
      - http:
          path: customers/{id}
          method: get
          cors: true

  getByCredit:
    handler: handlers/getAllByCredit.getAllByCredit
    events:
      - http:
          path: customersByCredit
          method: get
          cors: true

  update:
    handler: handlers/update.update
    events:
      - http:
          path: customers/{id}
          method: put
          cors: true

  delete:
    handler: handlers/delete.delete
    events:
      - http:
          path: customers/{id}
          method: delete
          cors: true

  putcredit:
    handler: handlers/putCredit.putCredit
    events:
      - http:
          path: credit/{id}
          method: put
          cors: true

resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.customersTableName}
